# Site settings
title: SWA Notes
email: mikederksen5@live.nl
description: Notes for SWA class
baseurl: ""
url: "http://swa.miked.nl"
github_username:  mikederksen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"